version: '3'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
  redis:
    image: redis:6.2.4-alpine
    restart: on-failure
    ports:
      - 6379:6379
